# -*- coding: utf-8 -*-
"""AICustomerSupport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ueU0yTNMulA9U8wrfp-RGON97eGSV5G
"""

# SETUP
# ===============================================================
!pip install -q sentence-transformers gradio openai

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import time
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

try:
    plt.style.use('seaborn-v0_8-whitegrid')
except OSError:
    try:
        plt.style.use('seaborn-whitegrid')
    except OSError:
        pass
sns.set_palette('colorblind')

print("=" * 60)
print("  All libraries installed and imported successfully!")
print("  Ready for the masterclass.")
print("=" * 60)

# LOAD DATA — using the real Kaggle "Customer Support Ticket Dataset"
# ===============================================================
import os

loaded = False
for source, path in [
    ("current directory", "customer_support_tickets.csv"),
    ("Materials folder", "Materials/customer_support_tickets.csv"),
    ("Colab upload", "/content/customer_support_tickets.csv"),
]:
    try:
        raw = pd.read_csv(path)
        print(f"Loaded dataset from {source}.")
        loaded = True
        break
    except Exception:
        continue

if not loaded:
    raise FileNotFoundError(
        "Could not find customer_support_tickets.csv.\n"
        "Upload it to Colab: click the folder icon in the left sidebar -> Upload."
    )

# Rename to match the rest of the notebook's lowercase_underscore convention
tickets = raw.rename(columns={
    "Ticket ID": "ticket_id",
    "Ticket Type": "ticket_type",
    "Ticket Subject": "ticket_subject",
    "Ticket Description": "ticket_description",
    "Product Purchased": "product_purchased",
    "Ticket Priority": "ticket_priority",
    "Ticket Channel": "ticket_channel",
    "Customer Satisfaction Rating": "customer_satisfaction",
})

print()
print(f"Dataset: {tickets.shape[0]:,} support tickets")
print(f"Columns: {list(tickets.columns)}")
print()
tickets.head()

# TICKET CATEGORIES
# ===============================================================
print("=" * 60)
print("  TICKET CATEGORIES")
print("  (What agents spend all day manually sorting)")
print("=" * 60)
print()

category_counts = tickets['ticket_type'].value_counts()
print(category_counts)
print()

fig, ax = plt.subplots(figsize=(10, 5))
category_counts.plot(kind='barh', ax=ax, color='#ED1C24', edgecolor='none')
ax.set_title('Distribution of Support Ticket Types', fontsize=14, fontweight='bold')
ax.set_xlabel('Number of Tickets')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
for i, v in enumerate(category_counts.values):
    ax.text(v + 15, i, str(v), va='center', fontweight='bold')
plt.tight_layout()
plt.show()

# SAMPLE TICKETS
# ===============================================================
print("=" * 60)
print("  SAMPLE TICKETS (What humans have to read and classify)")
print("=" * 60)

for idx, row in tickets.sample(5, random_state=42).iterrows():
    print(f"\nTicket {row['ticket_id']} | Priority: {row['ticket_priority']}")
    print(f"  Category: {row['ticket_type']}")
    print(f"  Subject:  {row['ticket_subject']}")
    print(f"  Text:     {str(row['ticket_description'])[:150]}...")
    print("-" * 60)
# THE "OBVIOUS" KEYWORD APPROACH — adapted to this dataset's 5 categories
# ===============================================================
def keyword_classify(text):
    """The 'obvious' approach that doesn't work well."""
    text = str(text).lower()

    if any(word in text for word in ['bill', 'charge', 'invoice', 'payment', 'price']):
        return 'Billing inquiry'
    elif any(word in text for word in ['crash', 'error', 'bug', 'slow', 'broken', 'fix', 'not working']):
        return 'Technical issue'
    elif any(word in text for word in ['cancel', 'terminate', 'close my account', 'stop my subscription']):
        return 'Cancellation request'
    elif any(word in text for word in ['refund', 'money back', 'reimburse']):
        return 'Refund request'
    elif any(word in text for word in ['feature', 'how to', 'upgrade', 'plan', 'compatible']):
        return 'Product inquiry'
    else:
        return 'Unknown'

tickets['keyword_prediction'] = tickets['ticket_description'].apply(keyword_classify)

correct = (tickets['keyword_prediction'] == tickets['ticket_type']).sum()
total = len(tickets)
unknown = (tickets['keyword_prediction'] == 'Unknown').sum()

print("=" * 60)
print("  KEYWORD MATCHING RESULTS")
print("=" * 60)
print(f"\n  Accuracy: {correct}/{total} = {correct/total:.1%}")
print(f"  Classified as 'Unknown': {unknown} tickets ({unknown/total:.1%})")
print(f"\n  That means {total - correct} tickets would be MISROUTED.")
print(f"  At 10,000 tickets/month, that's ~{int((1 - correct/total) * 10000):,} wrong routings per month.")

# THE BREAKTHROUGH: A model that UNDERSTANDS language
# ===============================================================
from sentence_transformers import SentenceTransformer

start = time.time()
model = SentenceTransformer('all-MiniLM-L6-v2')
elapsed = time.time() - start

print(f"Model loaded in {elapsed:.1f} seconds!")
print(f"Embedding dimension: {model.get_sentence_embedding_dimension()}")

# What does an embedding actually look like?
# ===============================================================
sample_text = tickets['ticket_description'].iloc[0]
embedding = model.encode(sample_text)

print(f"Original text: '{sample_text[:80]}...'")
print(f"Embedding shape: {embedding.shape}")
print(f"\nFirst 20 numbers (out of {embedding.shape[0]}):")
print(embedding[:20].round(4))
print(f"\n...and {embedding.shape[0]-20} more numbers.")
print(f"\nEach number captures some aspect of the sentence's MEANING.")
print(f"Together, these {embedding.shape[0]} numbers form a unique 'fingerprint' for this sentence.")

# THE MAGIC: Similar meanings -> Similar numbers
# ===============================================================
sentences = [
    "My payment was charged twice",       # Billing
    "I see a duplicate charge on my card", # Billing (same meaning!)
    "The app crashes when I open settings", # Technical
    "Software keeps freezing on startup",   # Technical (same meaning!)
    "How do I cancel my subscription?",     # Cancellation (replaces "reset password" -> Account Access doesn't exist here)
]

labels = ["S1: Billing", "S2: Billing", "S3: Technical", "S4: Technical", "S5: Cancellation"]

embeddings_demo = model.encode(sentences)
similarity_matrix = cosine_similarity(embeddings_demo)

sim_df = pd.DataFrame(
    similarity_matrix.round(3),
    index=labels,
    columns=labels
)

print("COSINE SIMILARITY MATRIX")
print("(1.0 = identical meaning, 0.0 = completely unrelated)")
print()
for i, s in enumerate(sentences):
    print(f"  {labels[i]}: \"{s}\"")
print()
sim_df

#Visualize the similarity matrix as a heatmap
# ===============================================================
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(
    similarity_matrix,
    annot=True, fmt='.2f',
    xticklabels=[f'S{i+1}' for i in range(5)],
    yticklabels=[f'S{i+1}' for i in range(5)],
    cmap='RdYlGn', center=0.5,
    vmin=0, vmax=1,
    ax=ax
)
ax.set_title('Semantic Similarity: The Model KNOWS Which Tickets Are Related',
              fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

print("\nS1 ('payment charged twice') and S2 ('duplicate charge on card'):")
print(f"  -> Similarity: {similarity_matrix[0][1]:.3f}  (HIGH - same meaning!)")
print()
print("S1 ('payment charged twice') and S3 ('app crashes'):")
print(f"  -> Similarity: {similarity_matrix[0][2]:.3f}  (LOW - different topics)")
print()
print("The model understands meaning WITHOUT any keyword rules.")
print("This is what keyword matching could NEVER do.")

print(f"Generating embeddings for all {len(tickets):,} tickets...")
print("(This takes a few minutes on CPU for ~8,500 rows)")
print()

start = time.time()
all_embeddings = model.encode(
    tickets['ticket_description'].astype(str).tolist(),
    show_progress_bar=True,
    batch_size=64
)
elapsed = time.time() - start

print(f"\nDone! Generated in {elapsed:.1f} seconds")
print(f"Embeddings shape: {all_embeddings.shape}")
print(f"Each of the {all_embeddings.shape[0]} tickets is now a vector of {all_embeddings.shape[1]} numbers.")

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
embeddings_2d = tsne.fit_transform(all_embeddings)

fig, ax = plt.subplots(figsize=(14, 10))

categories = tickets['ticket_type'].unique()
colors = sns.color_palette('colorblind', len(categories))

for cat, color in zip(categories, colors):
    mask = tickets['ticket_type'] == cat
    ax.scatter(
        embeddings_2d[mask, 0],
        embeddings_2d[mask, 1],
        c=[color],
        label=cat,
        alpha=0.6,
        s=40,
        edgecolors='white',
        linewidth=0.5
    )

ax.set_title('8,469 Support Tickets — Automatically Clustered by MEANING',
              fontsize=16, fontweight='bold', pad=20)
ax.set_xlabel('t-SNE Dimension 1', fontsize=12)
ax.set_ylabel('t-SNE Dimension 2', fontsize=12)
ax.legend(title='Ticket Category', fontsize=11, title_fontsize=12,
          bbox_to_anchor=(1.05, 1), loc='upper left')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

fig.tight_layout()
plt.show()

print()
print("WITHOUT telling the model what the categories are,")
print("similar tickets have automatically grouped together.")
print()
print("Billing tickets cluster in one region.")
print("Technical issues cluster in another.")
print("The model figured out the categories from LANGUAGE ALONE.")

import plotly.express as px
import textwrap

wrapped_text = [
    "<br>".join(textwrap.wrap(str(text), width=60))
    for text in tickets['ticket_description']
]

df_plot = pd.DataFrame({
    't-SNE Dimension 1': embeddings_2d[:, 0],
    't-SNE Dimension 2': embeddings_2d[:, 1],
    'Ticket Category': tickets['ticket_type'],
    'Ticket Text': wrapped_text
})

fig = px.scatter(
    df_plot, x='t-SNE Dimension 1', y='t-SNE Dimension 2',
    color='Ticket Category', hover_data=['Ticket Text'],
    title='8,469 Support Tickets — Automatically Clustered by MEANING'
)
fig.show()

# PREPARE DATA FOR MACHINE LEARNING
# ===============================================================
X = all_embeddings              # 8,469 tickets x 384 dimensions
y = tickets['ticket_type'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training set: {X_train.shape[0]} tickets")
print(f"Test set:     {X_test.shape[0]} tickets")
print(f"Features per ticket: {X_train.shape[1]} (embedding dimensions)")
print(f"Categories: {sorted(set(y))}")

# TRAIN THE CLASSIFIER - Just 2 lines of ML!
# ===============================================================
start = time.time()
classifier = LogisticRegression(max_iter=1000, random_state=42)
classifier.fit(X_train, y_train)
train_time = time.time() - start

y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

# Compare to keyword matching from Act 1
keyword_correct = (tickets['keyword_prediction'] == tickets['ticket_type']).sum()
keyword_accuracy = keyword_correct / len(tickets)

print("=" * 60)
print(f"  EMBEDDING + CLASSIFIER ACCURACY: {accuracy:.1%}")
print(f"  Training time: {train_time:.2f} seconds")
print("=" * 60)
print()
print(f"  Compare to keyword matching from Act 1: {keyword_accuracy:.1%}")
print(f"  Improvement: +{(accuracy - keyword_accuracy) * 100:.1f} percentage points")
print()
print(f"  That's a massive improvement from just 2 lines of ML code.")
# DETAILED PERFORMANCE BY CATEGORY
# ===============================================================
print("Classification Report:")
print("(Precision = of tickets predicted as X, how many are actually X)")
print("(Recall    = of actual X tickets, how many did we correctly find)")
print()
print(classification_report(y_test, y_pred))

# CONFUSION MATRIX: Where does the model make mistakes?
# ===============================================================
fig, ax = plt.subplots(figsize=(10, 8))
cm = confusion_matrix(y_test, y_pred, labels=classifier.classes_)

sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=classifier.classes_,
    yticklabels=classifier.classes_,
    ax=ax
)

ax.set_title('Confusion Matrix: Where Does the Model Make Mistakes?',
              fontsize=14, fontweight='bold')
ax.set_xlabel('Predicted Category', fontsize=12)
ax.set_ylabel('Actual Category', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
fig.tight_layout()
plt.show()

print("\nHow to read this:")
print("  - Numbers on the DIAGONAL = correct predictions")
print("  - Numbers OFF the diagonal = mistakes")
print("  - Look for the largest off-diagonal numbers to find")
print("    which categories the model confuses most often.")

# THE FUN PART: Test on tickets the model has NEVER seen
# ===============================================================
test_tickets = [
    "I can't log into my account after changing my phone number",
    "Please refund my last two payments - the service was down for a week",
    "Does your platform integrate with Slack and Microsoft Teams?",
    "The dashboard takes over 30 seconds to load since the latest update",
    "I want to downgrade my plan from Pro to Basic, effective next month",
]

print("=" * 60)
print("  LIVE PREDICTIONS ON BRAND-NEW TICKETS")
print("=" * 60)

new_embeddings = model.encode(test_tickets)
predictions = classifier.predict(new_embeddings)
probabilities = classifier.predict_proba(new_embeddings)

for ticket, pred, probs in zip(test_tickets, predictions, probabilities):
    confidence = max(probs) * 100
    print(f"\nTicket: \"{ticket}\"")
    print(f"  -> Predicted: {pred}")
    print(f"  -> Confidence: {confidence:.0f}%")

    sorted_probs = sorted(zip(classifier.classes_, probs), key=lambda x: -x[1])
    for cat, prob in sorted_probs:
        bar = "\u2588" * int(prob * 30)
        print(f"    {cat:25s} {bar} {prob:.1%}")

# BUILD AN INTERACTIVE APP - Right here in the notebook!
# ===============================================================
import gradio as gr

def classify_ticket(ticket_text):
    """Classify a customer support ticket using our trained model."""
    if not ticket_text or not ticket_text.strip():
        return {"Please enter a ticket description": 1.0}

    # Generate embedding
    embedding = model.encode([ticket_text])

    # Predict with probabilities
    probabilities = classifier.predict_proba(embedding)[0]

    # Return as a dictionary for Gradio Label component
    results = {
        cat: float(prob)
        for cat, prob in zip(classifier.classes_, probabilities)
    }
    return results

# Create the Gradio interface
demo = gr.Interface(
    fn=classify_ticket,
    inputs=gr.Textbox(
        label="Paste a customer support ticket",
        placeholder="e.g., 'My account was charged twice this month and I need a refund'",
        lines=3,
    ),
    outputs=gr.Label(
        label="Predicted Category",
        num_top_classes=5,
    ),
    title="AI Customer Support Ticket Classifier",
    description=(
        "Paste any support ticket below and the AI will instantly categorize it. "
        "This uses the same embedding + classification pipeline we just built."
    ),
    examples=[
        ["My internet connection keeps dropping every few hours and I've restarted the router multiple times"],
        ["I was charged $49.99 but my plan is only $29.99 per month - please explain the extra charge"],
        ["How do I export my project data to CSV format?"],
        ["I want to cancel my subscription - please process this immediately"],
        ["Please process a refund, the service was down for a full week"],
    ],
    theme=gr.themes.Soft()
)

print("Launching interactive app...")
print("Click the examples below or type your own ticket!")
demo.launch(share=True)